### PR TITLE
remove dnspython3 workarounds

### PR DESCRIPTION
**Pull request by peterdemin**
dnspython supports both Python 2 and Python 3 since Sep 30, 2016.
There is no need to differentiate between Python versions and
the wheel can be universal.

I used version 1.15.0 because it's current, but it might work with 1.12 too.

### CODE REVIEW

**Comment by peterdemin** [comment]
dnspython issue regarding Python3 support:
https://github.com/rthalley/dnspython/issues/170

**Comment by michaelherold** [comment]
Thanks for the contribution! Apologies for the lack of reply: I somehow managed to unwatch all of my repositories and didn't notice. 😞 

I'll get this merged and released soon!

**Comment by michaelherold** [comment]
Closed via 9852a78c85c877be13b0276c773d62f128702ea7.

**Comment by michaelherold** [comment]
Version 1.3.2 is now out with your change. Thanks again for the PR!

**Comment by peterdemin** [comment]
Thanks, Michael. This fix will save me a hustle when hard-pinning dependency versions with [pip-compile-multi](https://pypi.org/project/pip-compile-multi/) in Py2/3 compatible project.

**Pull request closed without merging**
